"""Late initial migration

Revision ID: 1f3b51ba7d4b
Revises: 
Create Date: 2021-03-20 17:52:12.287887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3b51ba7d4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('school_name', sa.String(length=100), nullable=False),
    sa.Column('video', sa.String(length=100), nullable=True),
    sa.Column('github', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('post', 'draft')
    op.drop_column('subscribed_user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribed_user', sa.Column('name', sa.VARCHAR(length=20), nullable=True))
    op.add_column('post', sa.Column('draft', sa.INTEGER(), nullable=True))
    op.drop_table('submission')
    # ### end Alembic commands ###
