"""Added Workshop

Revision ID: bb5cf344f5d6
Revises: 13f338b821f5
Create Date: 2021-04-27 21:56:16.434225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5cf344f5d6'
down_revision = '13f338b821f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workshop'))
    )
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('draft',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('draft',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('workshop')
    # ### end Alembic commands ###
